osrf/mbari_wec_gz

- CONTRIBUTING.md
- LICENSE
- buoy_description/QUALITY_DECLARATION.md
- buoy_description/package.xml
- buoy_gazebo/QUALITY_DECLARATION.md
- buoy_gazebo/launch/buoy.launch.py
- buoy_gazebo/package.xml
* `LICENSE` file
* License on both `packages.xml`s
* `CONTRIBUTING.md` file with license excerpt similar to various ROS 2 libraries (i.e. [rclc](https://github.com/ros2/rclc/blob/master/CONTRIBUTING.md)), but without the part about DCO for now
* `QUALITY_DECLARATION.md`: Updated various parts based on what's been already setup. Used [rclcpp](https://github.com/ros2/rclcpp/blob/master/rclcpp/QUALITY_DECLARATION.md) as a template.
With these changes, `colcon test` comes back clean:
```
$ colcon test --packages-select buoy_gazebo
```
```
Label Time Summary:
copyright     =   0.26 sec*proc (1 test)
flake8        =   0.23 sec*proc (1 test)
lint_cmake    =   0.16 sec*proc (1 test)
linter        =   1.09 sec*proc (5 tests)
pep257        =   0.18 sec*proc (1 test)
xmllint       =   0.26 sec*proc …
```
> Add license

- buoy_gazebo/CMakeLists.txt
- buoy_gazebo/hooks/buoy_gazebo.dsv.in
- buoy_gazebo/src/ElectroHydraulicSoln.hh
- buoy_gazebo/src/PTO_ElectroHydraulicState.hh
- buoy_gazebo/src/ProtoElectroHydraulicPTO.cc
- buoy_gazebo/src/ProtoElectroHydraulicPTO.hh
- buoy_gazebo/src/WindingCurrentTarget.hh
- buoy_gazebo/src/include/JustInterp/BilinearInterpolator.hpp
- buoy_gazebo/src/include/JustInterp/JustInterp.hpp
- buoy_gazebo/src/include/JustInterp/LinearInterpolator.hpp
- buoy_gazebo/src/include/JustInterp/TableInterpolator.hpp
- buoy_gazebo/src/include/JustInterp/Utils.hpp
- buoy_gazebo/worlds/mbari_wec.sdf
- buoy_gazebo/worlds/proto_electrohydraulicPTO.sdf
Porting plugins from bitbucket.
Install the project using instructions in [buoy_entrypoint](https://github.com/osrf/buoy_entrypoint) and run either
```
ros2 launch buoy_gazebo buoy.launch.py ign_args:="mbari_wec.sdf"
ros2 launch buoy_gazebo buoy.launch.py ign_args:="proto_electrohydraulicPTO.sdf"
```
> Porting electro-hydraulic plugin

- buoy_gazebo/worlds/electrohydraulicPTO.sdf
- buoy_gazebo/worlds/mbari_wec.sdf
- buoy_gazebo/worlds/pneumatic_spring.sdf
The SDF worlds are currently loading several world and GUI plugins which would be loaded by default anyway. We can reduce some boilerplate by just removing all plugins. We should only specify the plugins to load in case we want to load non-default plugins.
You can check that the world still work as before:
```
ign gazebo -v 2 mbari_wec.sdf
ign gazebo -v 2 electrohydraulicPTO.sdf
ign gazebo -v 2 pneumatic_spring.sdf
```
> Remove default plugins from SDF worlds

- .github/workflows/ci.yml
Ubuntu latest must have been updated recently to point to Jammy, which doesn't have ROS Galactic and makes our CI fail.
> Use Focal on CI (Ubuntu latest is Jammy now)

- buoy_gazebo/src/ElectroHydraulicPTO/ElectroHydraulicPTO.cc
- buoy_gazebo/src/ElectroHydraulicPTO/ElectroHydraulicPTO.hh
- buoy_gazebo/src/ElectroHydraulicPTO/ElectroHydraulicSoln.hh
- buoy_gazebo/src/ElectroHydraulicPTO/ElectroHydraulicState.hh
- buoy_gazebo/src/PolytropicPneumaticSpring/PolytropicPneumaticSpring.cc
- buoy_gazebo/src/PolytropicPneumaticSpring/PolytropicPneumaticSpring.hh
- buoy_gazebo/worlds/electrohydraulicPTO.sdf
- buoy_gazebo/worlds/mbari_wec.sdf
- buoy_gazebo/worlds/pneumatic_spring.sdf
Adopting some good practices:
* Classes belonging to this project should use the project's namespace. The `ignition::gazebo` namespace is reserved for code that's part of the core simulator and the plugins we officially distribute.
* Avoid `using namespace`s from other projects - this is something that ROS's default linters actually complain about
Using a single `buoy_gazebo` namespace instead of various nested namespaces should also help with appeasing both uncrustify and cpplint at the same time.
The PR should be easier to review if you hide whitespace changes.
> Use project-specific C++ namespaces

- buoy_gazebo/src/ElectroHydraulicPTO/ElectroHydraulicPTO.cpp
A little crash was introduced in #3. Try for example:
```
ros2 launch buoy_gazebo mbari_wec.launch.py
```
Then press play, and the simulation crashes.
Originally, the `rand()` function was used, but that resulted in this warning:
```
Consider using rand_r(...) instead of rand(...) for improved thread safety.  [runtime/threadsafe_fn] [2]
```
The proposed fix here is to use a fixed a seed when calling `rand_r`. This should make the simulation more deterministic, which is usually desirable. But if we really want a different value each time the simulation is run, we could seed it with the current time.
> Fix ElectroHydraulic crash

- buoy_description/models/mbari_wec/model.sdf.em
- buoy_gazebo/worlds/mbari_wec.sdf
The `WaterPlaneArea` joint is just a temporary trick to prevent the model from sinking. We'll remove it eventually, but until then, it would be convenient to move it out of the model, so that the model can be reused in other worlds without that trick.
I actually did this as part of #26 so that the playground world can have a different joint to the world. Moving it to a separate PR for quicker review, and to remove future conflicts when the joint is removed.
This change shouldn't change the behaviour of the `mbari_wec` world.
> Move joint to world out of model

- buoy_description/models/mbari_wec/model.sdf.em
- buoy_gazebo/worlds/mbari_wec.sdf
Adding Gazebo's [Buoyancy](https://gazebosim.org/api/gazebo/6.6/classignition_1_1gazebo_1_1systems_1_1Buoyancy.html#details) plugin to the world.
PTO and Heave Cone volume should come to `0.3139 m^3` and `0.1928 m^3`, respectively. Assuming buoy volume to be `~5.47 m^3` (using 1m height).
Also, updated center of buoyancy from [#31](https://github.com/osrf/buoy_sim/issues/31). Since collision won't be used for anything else right now, made heave cone and buoy collision geometry to be a cuboid, pto is using mesh.
- Graded buoyancy with water density `1025 km/m^3`
- Added water plane
- Removed WaterPlanarArea joint, buoy seems stable
To run: 
```
ign gazebo mbari_wec.sdf
```
> Adding buoyancy

- buoy_gazebo/CMakeLists.txt
- buoy_gazebo/gazebo/server.config
- buoy_gazebo/hooks/buoy_gazebo.dsv.in
- buoy_gazebo/worlds/mbari_wec.sdf
On #12 all world plugins were removed from the world files so we could load the defaults instead. But then on #33 we needed a non-default plugin, which meant we had to add all others.
This PR moves those plugins to a `server.config` file and points to that file using the `IGN_GAZEBO_SERVER_CONFIG_PATH`, so that becomes the new default set of plugins. This way, buoyancy will be enabled by default for all worlds.
It's still possible to override this config file by explicitly listing plugins inside each world file as needed.
There's more info about server configs on [this tutorial](https://gazebosim.org/api/gazebo/6.9/server_config.html).
Run
`ign gazebo mbari_wec.sdf -r`
The simulation should start and the buoy bounces up and down due to buoyancy.
> Move world plugins to a config file

- README.md
- buoy_gazebo/CMakeLists.txt
- buoy_gazebo/src/ElectroHydraulicPTO/ElectroHydraulicPTO.cpp
[Ignition Common's profiler](https://ignitionrobotics.org/api/common/4.4/profiler.html) is very handy to debug performance.
This PR just sets up the profiler and makes use of the existing profiling points.
See the snippet added to the README for how to enable and use it. In order to get profiling points coming from the Gazebo libraries themselves, they need to be compiled from source with `-DENABLE_PROFILER=1`.
Here's some example output. I was surprised to see that the `PolytropicPneumaticSpring` is taking up almost as much time as the physics' forward step.
> Setup profiler

- .github/workflows/build-and-test.sh
- buoy_tests/CMakeLists.txt
- buoy_tests/package.xml
- buoy_tests/tests/no_inputs.cpp
* Closes #37 
Created a new package to hold simulation-enabled tests.
I added a very simple test that checks that the buoy stays within bounds if no inputs are given. I'm only checking the position but we could extend it to check velocities, accelerations, etc.
The current test doesn't use ROS 2 at all. For ROS 2 enabled tests we'll likely use `launch_testing`. 
1. Compile with `colcon build --cmake-args -DBUILD_TESTING=true`
2. Run the test with one of these:
1. `colcon test --packages-select buoy_tests` - this will also run linters and in the future other tests
2. `./install/lib/buoy_tests/no_inputs` - this runs just the new test
> Add buoy_tests package and a simple test

- buoy_gazebo/worlds/buoy_playground.sdf
- buoy_gazebo/worlds/mbari_wec.sdf
* Requires https://github.com/gazebosim/gz-sim/pull/1534
Use the odometry publisher to get the transform from the buoy to the world.
> Add odometry publisher

- .github/workflows/build-and-test.sh
- buoy_tests/CMakeLists.txt
This should take care of the warning while building `buoy_tests` package.
```
[75.327s] WARNING:colcon.colcon_cmake.task.cmake.build:Could not run installation step for package 'buoy_tests' because it has no 'install' target
```
Modified the `BUILD_TESTING` flag logic. Ideally, `return()` should bring back control to the parent `CMakeLists.txt`, but here there is none which might be causing the issue.
> Removing colcon warning

- buoy_gazebo/CMakeLists.txt
- buoy_gazebo/src/ElectroHydraulicPTO/CMakeLists.txt
- buoy_gazebo/src/ElectroHydraulicPTO/ElectroHydraulicPTO.cpp
- buoy_gazebo/src/ElectroHydraulicPTO/ElectroHydraulicPTO.hpp
- buoy_gazebo/src/ElectroHydraulicPTO/ElectroHydraulicState.hpp
- buoy_gazebo/src/ElectroHydraulicPTO/WindingCurrentTarget.hpp
- buoy_gazebo/src/PolytropicPneumaticSpring/CMakeLists.txt
- buoy_gazebo/src/PolytropicPneumaticSpring/PolytropicPneumaticSpring.cpp
- buoy_gazebo/src/PolytropicPneumaticSpring/PolytropicPneumaticSpring.hpp
- buoy_gazebo/src/PolytropicPneumaticSpring/SpringState.hpp
- buoy_gazebo/src/buoy_utils/CMakeLists.txt
- buoy_gazebo/src/buoy_utils/CommandTriState.hpp
- buoy_gazebo/src/controllers/PowerController/CMakeLists.txt
- buoy_gazebo/src/controllers/PowerController/PowerController.cpp
- buoy_gazebo/src/controllers/PowerController/PowerController.hpp
- buoy_gazebo/src/controllers/SpringController/SpringController.cpp
- buoy_gazebo/worlds/mbari_wec.sdf
Addresses #30 #45
Power Controller should accept ROS2 commands via services and communicate commands to ElectroHydraulicPTO plugin.
Feedback -- Todo:
~~- [ ] Implement PowerController Status bit-field~~
Command -- Todo:
~~- [ ] `PCBattSwitchCommand` via `/pc_batt_switch_command`~~
~~- [ ] `PCChargeCurrLimCommand` via `/pc_charge_curr_lim_command`~~
~~- [ ] `PCDrawCurrLimCommand` via `/pc_draw_curr_lim_command`~~
~~- [ ] `PCStdDevTargCommand` via `/pc_std_dev_targ_command`~~
~~- [ ] `PCVTargMaxCommand` via `/pc_v_targ_max_command`~~
~~- [ ] `GainCommand` via `/gain_command`~~
~~- [x] `PCPackRateCommand` via `/pc_pack_rate_command`~~
> add PowerController ROS2 node

- buoy_description/CMakeLists.txt
- buoy_description/hooks/buoy_description.dsv.in
- buoy_description/models/mbari_wec_base/model.config
- buoy_description/models/mbari_wec_ros/model.config
- buoy_description/models/mbari_wec_ros/model.sdf
- buoy_gazebo/CMakeLists.txt
- buoy_gazebo/worlds/buoy_no_plugins.sdf
- Bug fix for robot_state_publisher dying, unable to find the model after reorganization.
```
Error [SDF.cc:160] Tried to use callback in sdf::findFile(), but the callback is empty.  Did you call sdf::setFindCallback()?
Error Code 13: [/sdf/world[@name="world_demo"]/model[@name="MBARI_WEC_ROS"]/include[0]/uri:/home/anderson/wec/igngzb/openrobotics/workspace/src/buoy_sim/buoy_gazebo/worlds/mbari_wec.sdf:L49]: Msg: Unable to find 
```
- Updating other worlds, launch files and making sure they work as expected.
> Updating worlds after model reorg

- buoy_gazebo/CMakeLists.txt
- buoy_gazebo/src/buoy_utils/CMakeLists.txt
- buoy_gazebo/src/buoy_utils/Stopwatch.cpp
- buoy_gazebo/src/buoy_utils/Stopwatch.hpp
- buoy_gazebo/src/controllers/PowerController/CMakeLists.txt
- buoy_gazebo/src/controllers/PowerController/PowerController.cpp
- buoy_gazebo/src/controllers/SpringController/CMakeLists.txt
- buoy_gazebo/src/controllers/SpringController/SpringController.cpp
- buoy_gazebo/test/test_stopwatch.cpp
PR to add `Stopwatch` to `ros_ign_gazebo`:
https://github.com/gazebosim/ros_gz/pull/287
Adding those changes and tests here in the mean-time
> Updates/tests from ros_ign_gazebo::Stopwatch PR

- buoy_description/models/mbari_wec/model.sdf
- buoy_gazebo/src/PolytropicPneumaticSpring/PolytropicPneumaticSpring.cpp
- buoy_gazebo/src/PolytropicPneumaticSpring/PolytropicPneumaticSpring.hpp
- buoy_tests/CMakeLists.txt
- buoy_tests/launch/pc_commands_ros_feedback.launch.py
- buoy_tests/launch/pc_commands_ros_feedback_py.launch.py
- buoy_tests/launch/sc_commands_ros_feedback.launch.py
- buoy_tests/launch/sc_pump_ros_feedback_py.launch.py
- buoy_tests/launch/sc_valve_ros_feedback_py.launch.py
- buoy_tests/tests/experiment_comparison.cpp
- buoy_tests/tests/pc_commands_ros_feedback.cpp
- buoy_tests/tests/sc_commands_ros_feedback.cpp
- buoy_tests/worlds/TestMachine.sdf
The spring model was causing some jitter in the piston position, spring pressures, as well as the force-torque sensor. This was due to a discontinuity in pressures in the implementation of hysteresis in the spring. This agitation in forces occurred for very small velocities (based on changes of sign). A dead-band was added to checking velocity to fix this. Also, pressure now evolves continuously across the hysteresis rather than a step change.
Additionally, to better model the thermal decay of pressure at low speeds, a cooling law has been implemented within the velocity dead-band.
> Refine Spring

- buoy_gazebo/src/ElectroHydraulicPTO/ElectroHydraulicPTO.cpp
- buoy_gazebo/src/ElectroHydraulicPTO/ElectroHydraulicSoln.hpp
- buoy_tests/launch/experiment_comparison_select.launch.py
This is a very simple fix of a constant in the electro-hydraulic PTO that had been set wrong.   I re-established the experiment_comparison tests and they're passing.
Unfort, sc_commands_ros_feedback test if failing, I'm hoping @andermi can take a look and see why that is.  It broke it before too, so if there's something obvious causing problems please let me know.
> Fix batt curr

- .github/workflows/build-and-test.sh
- buoy_tests/tests/fixture_server.cpp
- buoy_tests/tests/pc_commands_ros_feedback.cpp
I changed some asserts to expects which I think was causing it to bomb out early and then timeout when launch_test didn't notice it exited.
> Fix flaky PC commands test

- buoy_gazebo/launch/mbari_wec.launch.py
- buoy_gazebo/scripts/mbari_wec_batch
Inadvertently broke the original `mbari_wec.launch.py` when adding some args from batching
> fix `mbari_wec.launch.py` launch args

- buoy_description/models/mbari_wec_ros/model.sdf
- buoy_gazebo/src/ElectroHydraulicPTO/BatteryState.hpp
- buoy_gazebo/src/ElectroHydraulicPTO/ElectroHydraulicPTO.cpp
- buoy_gazebo/src/controllers/BatteryController/BatteryController.cpp
- buoy_gazebo/src/controllers/BatteryController/BatteryController.hpp
- buoy_gazebo/src/controllers/BatteryController/CMakeLists.txt
Battery controller for simulating battery messages via BCRecord.msg.
```
$ ros2 topic echo /battery_data
header:
stamp:
sec: 0
nanosec: 68000000
frame_id: ''
seq_num: 0
voltage: 325.0
ips: 0.0
vbalance: 2.759999990463257
vstopcharge: 2.7899999618530273
gfault: 0.05999999865889549
hydrogen: 3.259999990463257
status: 11264
```
> Adding battery controller

- buoy_description/models/mbari_wec_base/model.sdf.em
- buoy_description/models/mbari_wec_ros/model.sdf
- buoy_gazebo/gazebo/server.config
- buoy_gazebo/src/controllers/TrefoilController/CMakeLists.txt
- buoy_gazebo/src/controllers/TrefoilController/TrefoilController.cpp
- buoy_gazebo/src/controllers/TrefoilController/TrefoilController.hpp
Trefoil controller for publishing IMU, Magnetometer, Sea pressure and other constants from TFRecord.msg
> Adding trefoil controller

- buoy_description/package.xml
- buoy_gazebo/package.xml
- buoy_tests/CMakeLists.txt
- buoy_tests/launch/sc_commands_ros_feedback.launch.py
- buoy_tests/package.xml
Apologies if I missed or miscredited anyone 🙏
Added maintainers and authors in alphabetical order, depending on contributors of each package (or rather everyone should be added in every package?).
Notes:
- Need Louise's and Joan's current/preferred email
- Added Rob in buoy_gazebo to credit for `mbari_wec`
> Updating package maintainers

- buoy_gazebo/src/controllers/PowerController/PowerController.cpp
- buoy_gazebo/src/controllers/SpringController/SpringController.cpp
Needs https://github.com/osrf/mbari_wec_utils/pull/50
fixed the error:
```
terminate called without an active exception
Aborted (core dumped)
```
but still get a segfault every so often with all subcommands of pbcmd
> Fix pbcmd terminate

- buoy_gazebo/worlds/buoy_no_plugins.sdf
- buoy_gazebo/worlds/buoy_playground.sdf
- buoy_gazebo/worlds/electrohydraulicPTO.sdf
- buoy_gazebo/worlds/mbari_wec.sdf.em
- buoy_gazebo/worlds/mbari_wec_sinusoidal_piston.sdf
- buoy_gazebo/worlds/pneumatic_spring.sdf
- buoy_gazebo/worlds/test_viscous_drag.sdf
- buoy_tests/worlds/TestMachine.sdf
- buoy_tests/worlds/singlefloatingbody_heave.sdf
- buoy_tests/worlds/singlefloatingbody_pitch.sdf
This warning was being spammed:
```
[Wrn] [Magnetometer.cc:433] Failed to update NavSat sensor enity [84]. Spherical coordinates not set.
```
This PR adds a `spherical_coordinates` to the main world file to init world origin and the warning goes away.
> Init latlon for world

- buoy_gazebo/src/IncidentWaves/IncidentWaves.cpp
- buoy_gazebo/src/buoy_utils/Rate.hpp
- buoy_gazebo/src/controllers/BatteryController/BatteryController.cpp
- buoy_gazebo/src/controllers/PowerController/PowerController.cpp
- buoy_gazebo/src/controllers/SpringController/SpringController.cpp
- buoy_gazebo/src/controllers/TrefoilController/TrefoilController.cpp
- buoy_gazebo/src/controllers/XBowAHRS/CMakeLists.txt
- buoy_gazebo/src/controllers/XBowAHRS/XBowAHRS.cpp
add sim-time-aware Rate class for controlling publishing in all controllers
> Fix logging rates

- buoy_description/models/mbari_wec/model.sdf.em
- buoy_description/models/mbari_wec_base/model.sdf.em
- buoy_gazebo/gazebo/server.config
- buoy_gazebo/launch/mbari_wec.launch.py
- buoy_gazebo/package.xml
- buoy_gazebo/scripts/mbari_wec_batch
- buoy_gazebo/src/IncidentWaves/IncidentWaves.cpp
- buoy_gazebo/src/buoy_utils/Rate.hpp
- buoy_gazebo/src/controllers/BatteryController/BatteryController.cpp
- buoy_gazebo/src/controllers/PowerController/PowerController.cpp
- buoy_gazebo/src/controllers/SpringController/SpringController.cpp
- buoy_gazebo/src/controllers/TrefoilController/TrefoilController.cpp
- buoy_gazebo/src/controllers/XBowAHRS/CMakeLists.txt
- buoy_gazebo/src/controllers/XBowAHRS/XBowAHRS.cpp
- buoy_gazebo/worlds/mbari_wec.sdf.em
added to batching and standard launch
requires:
https://github.com/osrf/mbari_wec_utils/pull/44 <-- https://github.com/osrf/mbari_wec_utils/pull/47
> add support for pblog

- .github/workflows/build-and-test.sh
Changed build-and-test.sh to use v1.3.0 of the free-surface hydro library.  At this time CI is cloning the repo and not using the ppa/debians/apt-get.  This is fine but it was using the latest main branch, so this change makes that more specific.  There is an PR associated with this one in mbari_wec that should be merged at the same time, that PR is just documentation changes to match...
> Modified to use fshydro v1.3.0 in CI

- buoy_gazebo/scripts/mbari_wec_batch
`matrix_mode: False` for vectorized batch params instead of meshgrid
> add matrix_mode: False option to sim params yaml to allow vectorized batch params

- buoy_description/models/mbari_wec/model.sdf.em
- buoy_gazebo/src/ElectroHydraulicPTO/ElectroHydraulicPTO.cpp
- buoy_gazebo/src/WaveBodyInteractions/WaveBodyInteractions.cpp
Right now, if we want to see debug statements from another plugin, WaveBodyInteractions produces so much output, that it is difficult to see other prints. Also, logging easily fills up disk space in `~/.gz/sim/log`. So, move gzdbg messages for the WaveBodyInteractions plugin behind debug flag.
> Debug flag for WaveBodyInteractions plugin

- .gitattributes
very minor and pedantic problem... GitHub was labeling our project as primarily SciLab langage due to our bench test `*.tst` data
this PR fixes that:
```
$ github-linguist
68.07%  C++
28.85%  Python
2.65%   CMake
0.43%   Shell
```
> Fix GitHub detected languages

- buoy_gazebo/launch/mbari_wec.launch.py
override arguments weren't displayed in `-s` option of launch file
typo in inc wave override description
> Fix mbari_wec.launch.py arguments

- buoy_gazebo/src/LatentData/LatentData/LatentData.hpp
- buoy_gazebo/src/LatentData/LatentData/LatentDataPublisher.cpp
- buoy_gazebo/src/WaveBodyInteractions/WaveBodyInteractions.cpp
requires osrf/mbari_wec_utils#57
> Add wave body total power to latent data
